openapi: 3.0.3
info:
  title: Click App API
  description: API for managing click counts of different colors
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:3001
    description: Local server
tags:
  - name: ClickApi
    description: Click api 
paths:
  /clickApp:
    get:
      summary: Retrieve click count of a color
      parameters:
        - in: query
          name: color
          schema:
            type: string
          required: true
          description: The color for which to retrieve the click count
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the request was successful
                  color:
                    type: string
                    description: The color for which the click count is retrieved
                  count:
                    type: integer
                    description: The number of clicks for the specified color
                  message:
                    type: string
                    description: A message indicating the status of the request

    post:
      summary: Insert click data for all colors of a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                time:
                  type: string
                  description: The time of the click
                date:
                  type: string
                  description: The date of the click
                username:
                  type: string
                  description: The username of the user
                clickCounts:
                  type: object
                  description: Object containing click counts for different colors
              required:
                - time
                - date
                - username
                - clickCounts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Indicates if the request was successful
                  message:
                    type: string
                    description: A message indicating the status of the request

  /healthz:
    summary: Healthcheck endpoint
    get:
      summary: Healthcheck
      operationId: Healthcheck
      responses:
        "200":
          description: Healthy response