openapi: 3.0.3
info:
  title: Click Count API
  description: API to retrieve and insert click count data
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:3001
    description: Local server
tags:
  - name: ClickApi
    description: Click api 
paths:
  /ClickApp:
    summary: Retrieve click count data
    get:
      parameters:
        - in: query
          name: color
          schema:
            type: string
          description: Color parameter to filter click count data
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  count:
                    type: integer
                  message:
                    type: string
    post:
      summary: Insert click count data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                time:
                  type: string
                  format: date-time
                date:
                  type: string
                  format: date
                username:
                  type: string
                clickCounts:
                  type: object
                  additionalProperties:
                    type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
